gh-set-secrete

on:
  push:

#env:
    #AWS_REGION: us-west-2
    #SAGEMAKER_PIPELINE_ROLE_ARN: arn:aws:iam::882009174391:role/service-role/AmazonSageMakerServiceCatalogProductsUseRole
    #EXPERIMENT_CONFIG_FILE: experiment_config.csv
env:
  rep_acc_token: ${{ secrets.REPO_ACCESS_TOKEN }} # Permissions: repo (all) and read:org
  secret_name: HELLO_WORLD
  secret_body: "Hello World!"
  secret_environment: Deploy

jobs:
  gh-set-secret:
    runs-on: ubuntu-latest
    steps:
      - name: gh auth login
        shell: bash
        run: gh auth login --with-token <<< $rep_acc_token
      - name: gh secret set env
        shell: bash
        run: |
          repository='${{ github.repository }}'
          echo $repository
          gh secret set "$secret_name" --env "$secret_environment" --body "$secret_body" --repo $repository
  gh-test-secret:
    needs: [gh-set-secret]
    runs-on: ubuntu-latest
    environment:
      name: sandbox
    env:
      secret: ${{ secrets.HELLO_WORLD }}
    steps:
      - name: echo secret
        shell: bash
        run: |
          echo "Secret: $secret"
